apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: task
  labels:
    app: task
data:
  activity_service_addr: "_grpc._tcp.activity-service.activity.svc.cluster.local"
  project_service_addr: "_grpc._tcp.project-service.project.svc.cluster.local"
  user_service_addr: "_grpc._tcp.user-service.user.svc.cluster.local"
