apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  namespace: task
  labels:
    app: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: asia.gcr.io/stable-device-253005/go-grpc-microservices-task
          imagePullPolicy: Always
          env:
            - name: ACTIVITY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: activity_service_addr
            - name: PROJECT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: project_service_addr
            - name: USER_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: user_service_addr
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
