apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: task-rule
  namespace: task
spec:
  host: task-service.task.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
