apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project
  labels:
    app: project
data:
  activity_service_addr: "_grpc._tcp.activity-service.activity.svc.cluster.local"
  user_service_addr: "_grpc._tcp.user-service.user.svc.cluster.local"
