apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: project
  labels:
    app: project
spec:
  selector:
    app: project
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
