apiVersion: v1
kind: Namespace
metadata:
  name: activity
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: front
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: project
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: task
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: user
  labels:
    istio-injection: enabled
