apiVersion: v1
kind: Namespace
metadata:
  name: activity
---
apiVersion: v1
kind: Namespace
metadata:
  name: front
---
apiVersion: v1
kind: Namespace
metadata:
  name: project
---
apiVersion: v1
kind: Namespace
metadata:
  name: task
---
apiVersion: v1
kind: Namespace
metadata:
  name: user
