apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: user
  labels:
    app: user
data:
  activity_service_addr: "_grpc._tcp.activity-service.activity.svc.cluster.local"
  project_service_addr: "_grpc._tcp.project-service.project.svc.cluster.local"
