apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: asia.gcr.io/stable-device-253005/go-grpc-microservices-user
          imagePullPolicy: Always
          env:
            - name: ACTIVITY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: activity_service_addr
            - name: PROJECT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: project_service_addr
          ports:
            - name: grpc-port
              containerPort: 50051
              protocol: TCP
