apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user
  labels:
    app: user
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc-port
      protocol: TCP
