apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
  namespace: activity
  labels:
    app: activity
spec:
  replicas: 6
  selector:
    matchLabels:
      app: activity
  template:
    metadata:
      labels:
        app: activity
        version: v1
    spec:
      containers:
        - name: activity
          image: asia.gcr.io/gentle-current-254006/micro-activity
          imagePullPolicy: Always
          env:
            - name: USER_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: activity-config
                  key: user_service_addr
          ports:
            - name: grpc-port
              containerPort: 50051
              protocol: TCP
